<a href="https://colab.research.google.com/github/AremyDiaz/Regresion_Logistica/blob/main/A7_OtrosExperimentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Actividad de regresión logística

In [51]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [52]:
#Se lee el archivo
df=pd.read_csv('BD_Socio formador (TrainingDataComplete).csv', index_col='Id')
df.head()

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                          
1   1303834   23           3         single          rented            no   
2   7574516   40          10         single          rented            no   
3   3991815   66           4        married          rented            no   
4   6256451   41           2         single          rented           yes   
5   5768871   47          11         single          rented            no   

             Profession                 CITY           STATE  CURRENT_JOB_YRS  \
Id                                                                              
1   Mechanical_engineer                 Rewa  Madhya_Pradesh                3   
2    Software_Developer             Parbhani     Maharashtra                9   
3      Technical_writer            Alappuzha          Kerala                4   
4    Software_Developer          Bhubaneswar          Odisha                2   
5         Civil_servant  Tiruchirappalli[10]      Tamil_Nadu                3   

    CURRENT_HOUSE_YRS  Risk_Flag  
Id                                
1                  13          0  
2                  13          0  
3                  10          0  
4                  12          1  
5                  14          1

##Experimentos

Expermiento #1

In [426]:
#verificar los valores sin repartirse de una columna
unico = np.unique(df['Age'])
unico

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79])

In [54]:
df['Age'].median()

50.0

In [427]:
df['Age_bool']=np.where(df['Age']>df['Age'].median(), 1, 0)
df

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                              
1       1303834   23           3         single          rented            no   
2       7574516   40          10         single          rented            no   
3       3991815   66           4        married          rented            no   
4       6256451   41           2         single          rented           yes   
5       5768871   47          11         single          rented            no   
...         ...  ...         ...            ...             ...           ...   
251996  8154883   43          13         single          rented            no   
251997  2843572   26          10         single          rented            no   
251998  4522448   46           7         single          rented            no   
251999  6507128   45           0         single          rented            no   
252000  9070230   70          17         single          rented            no   

                 Profession                 CITY           STATE  \
Id                                                                 
1       Mechanical_engineer                 Rewa  Madhya_Pradesh   
2        Software_Developer             Parbhani     Maharashtra   
3          Technical_writer            Alappuzha          Kerala   
4        Software_Developer          Bhubaneswar          Odisha   
5             Civil_servant  Tiruchirappalli[10]      Tamil_Nadu   
...                     ...                  ...             ...   
251996              Surgeon              Kolkata     West_Bengal   
251997         Army_officer                 Rewa  Madhya_Pradesh   
251998      Design_Engineer      Kalyan-Dombivli     Maharashtra   
251999     Graphic_Designer          Pondicherry      Puducherry   
252000         Statistician                Avadi      Tamil_Nadu   

        CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  Risk_Flag  Age_bool  
Id                                                               
1                     3                 13          0         0  
2                     9                 13          0         0  
3                     4                 10          0         1  
4                     2                 12          1         0  
5                     3                 14          1         0  
...                 ...                ...        ...       ...  
251996                6                 11          0         0  
251997                6                 11          0         0  
251998                7                 12          0         0  
251999                0                 10          0         0  
252000                7                 11          0         1  

[252000 rows x 13 columns]

In [428]:
#Declarar variables
Vars_Indep= df[['CURRENT_HOUSE_YRS']]
Var_Dep= df['Age_bool']

#Redefinir variables
x= Vars_Indep
y= Var_Dep

#Dividir el conjunto de datos en la parte de entrenamiento y prueba:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba,
#solo se escala una variable y de tipo dicotonimca
x_train = escalar.fit_transform(x_train)
x_test = escalar.fit_transform(x_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenaar el modelo
algoritmo.fit(x_train, y_train)

LogisticRegression()

In [429]:
#Realizamos una predicción
y_pred = algoritmo.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [430]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusiòn: ')
print(matriz)

Matriz de Confusiòn: 
[[21016  4755]
 [19888  4741]]


In [431]:
#Calculo de la presición del modelo
#para tener una mejor precisión debemos de cambiar el numero de variables predictoras (y)
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average= "binary", pos_label=0)
print('Precisión de modelo: ')
print(precision)

Precisión de modelo: 
0.5137883825542734


In [432]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo: ')
print(exactitud)

Exactitud del modelo: 
0.5110515873015873


In [433]:
#calculo de la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred, average='binary', pos_label=0)
print('sensibilidad del modelo:')
print(sensibilidad)

sensibilidad del modelo:
0.8154902797718365


In [434]:
#El puntaje F1 que es una combinación entre la precisión y la sensibilidad,
#Calculo el puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajeF1=f1_score(y_test,y_pred,average='binary',pos_label=0)
print('Puntaje F1 del modelo')
print(puntajeF1)

Puntaje F1 del modelo
0.6304011998500186


Experimento #2

In [27]:
#Experiencia promedio
round(df['Experience'].mean())

10

In [28]:
df['Experience_bool']=np.where(df['Experience']>round(df['Experience'].mean()), 1, 0)
df

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                              
1       1303834   23           3         single          rented            no   
2       7574516   40          10         single          rented            no   
3       3991815   66           4        married          rented            no   
4       6256451   41           2         single          rented           yes   
5       5768871   47          11         single          rented            no   
...         ...  ...         ...            ...             ...           ...   
251996  8154883   43          13         single          rented            no   
251997  2843572   26          10         single          rented            no   
251998  4522448   46           7         single          rented            no   
251999  6507128   45           0         single          rented            no   
252000  9070230   70          17         single          rented            no   

                 Profession                 CITY           STATE  \
Id                                                                 
1       Mechanical_engineer                 Rewa  Madhya_Pradesh   
2        Software_Developer             Parbhani     Maharashtra   
3          Technical_writer            Alappuzha          Kerala   
4        Software_Developer          Bhubaneswar          Odisha   
5             Civil_servant  Tiruchirappalli[10]      Tamil_Nadu   
...                     ...                  ...             ...   
251996              Surgeon              Kolkata     West_Bengal   
251997         Army_officer                 Rewa  Madhya_Pradesh   
251998      Design_Engineer      Kalyan-Dombivli     Maharashtra   
251999     Graphic_Designer          Pondicherry      Puducherry   
252000         Statistician                Avadi      Tamil_Nadu   

        CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  Risk_Flag  Experience_bool  \
Id                                                                       
1                     3                 13          0                0   
2                     9                 13          0                0   
3                     4                 10          0                0   
4                     2                 12          1                0   
5                     3                 14          1                1   
...                 ...                ...        ...              ...   
251996                6                 11          0                1   
251997                6                 11          0                0   
251998                7                 12          0                0   
251999                0                 10          0                0   
252000                7                 11          0                1   

        Income_bool  
Id                   
1                 0  
2                 1  
3                 0  
4                 1  
5                 1  
...             ...  
251996            1  
251997            0  
251998            0  
251999            1  
252000            1  

[252000 rows x 14 columns]

In [29]:
#Declarar variables
Vars_Indep= df[['Income','CURRENT_HOUSE_YRS']]
Var_Dep= df['Experience_bool']

#Redefinir las variables
x= Vars_Indep
y= Var_Dep

#Dividir el conjunto de datos en la parte de entrenamiento y prueba:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba,
#solo se escala una variable y de tipo dicotonimca
x_train = escalar.fit_transform(x_train)
x_test = escalar.fit_transform(x_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenar el modelo
algoritmo.fit(x_train, y_train)

LogisticRegression()

In [30]:
#Realizar una predicción
y_pred = algoritmo.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [31]:
#Verificar la matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[25760   526]
 [23615   499]]


In [32]:
#Cálculo de la presición del modelo
#para tener una mejor precisión debemos de cambiar el numero de variables predictoras (y)
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average= "binary", pos_label=0)
print('Precisión de modelo: ')
print(precision)

Precisión de modelo: 
0.5217215189873418


In [33]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo: ')
print(exactitud)

Exactitud del modelo: 
0.5210119047619047


In [34]:
#calculo de la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred, average='binary', pos_label=0)
print('sensibilidad del modelo:')
print(sensibilidad)

sensibilidad del modelo:
0.9799893479418702


In [35]:
#El puntaje F1 que es una combinación entre la precisión y la sensibilidad,
#Calculo el puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajeF1=f1_score(y_test,y_pred,average='binary',pos_label=0)
print('Puntaje F1 del modelo')
print(puntajeF1)

Puntaje F1 del modelo
0.6809320521801192


Experimento 3

In [55]:
round(df['Income'].mean())

4997117

In [36]:
df['Income_bool']=np.where(df['Income']>round(df['Income'].mean()), 1, 0)
df

Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
Id                                                                              
1       1303834   23           3         single          rented            no   
2       7574516   40          10         single          rented            no   
3       3991815   66           4        married          rented            no   
4       6256451   41           2         single          rented           yes   
5       5768871   47          11         single          rented            no   
...         ...  ...         ...            ...             ...           ...   
251996  8154883   43          13         single          rented            no   
251997  2843572   26          10         single          rented            no   
251998  4522448   46           7         single          rented            no   
251999  6507128   45           0         single          rented            no   
252000  9070230   70          17         single          rented            no   

                 Profession                 CITY           STATE  \
Id                                                                 
1       Mechanical_engineer                 Rewa  Madhya_Pradesh   
2        Software_Developer             Parbhani     Maharashtra   
3          Technical_writer            Alappuzha          Kerala   
4        Software_Developer          Bhubaneswar          Odisha   
5             Civil_servant  Tiruchirappalli[10]      Tamil_Nadu   
...                     ...                  ...             ...   
251996              Surgeon              Kolkata     West_Bengal   
251997         Army_officer                 Rewa  Madhya_Pradesh   
251998      Design_Engineer      Kalyan-Dombivli     Maharashtra   
251999     Graphic_Designer          Pondicherry      Puducherry   
252000         Statistician                Avadi      Tamil_Nadu   

        CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  Risk_Flag  Experience_bool  \
Id                                                                       
1                     3                 13          0                0   
2                     9                 13          0                0   
3                     4                 10          0                0   
4                     2                 12          1                0   
5                     3                 14          1                1   
...                 ...                ...        ...              ...   
251996                6                 11          0                1   
251997                6                 11          0                0   
251998                7                 12          0                0   
251999                0                 10          0                0   
252000                7                 11          0                1   

        Income_bool  
Id                   
1                 0  
2                 1  
3                 0  
4                 1  
5                 1  
...             ...  
251996            1  
251997            0  
251998            0  
251999            1  
252000            1  

[252000 rows x 14 columns]

In [37]:
#Declarar variables
Vars_Indep= df[['Age']]
Var_Dep= df['Income_bool']

#Redefinir las variables
x= Vars_Indep
y= Var_Dep

#Dividir el conjunto de datos en la parte de entrenamiento y prueba:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba,
#solo se escala una variable y de tipo dicotonimca
x_train = escalar.fit_transform(x_train)
x_test = escalar.fit_transform(x_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenar el modelo
algoritmo.fit(x_train, y_train)

LogisticRegression()

In [38]:
#Realizar una predicción
y_pred = algoritmo.predict(x_test)
y_pred

array([1, 0, 0, ..., 1, 0, 1])

In [39]:
#Verificar la matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[12062 13142]
 [11778 13418]]


In [40]:
#Cálculo de la presición del modelo
#para tener una mejor precisión debemos de cambiar el numero de variables predictoras (y)
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average= "binary", pos_label=0)
print('Precisión de modelo: ')
print(precision)

Precisión de modelo: 
0.5059563758389262


In [41]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo: ')
print(exactitud)

Exactitud del modelo: 
0.5055555555555555


In [42]:
#calculo de la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred, average='binary', pos_label=0)
print('sensibilidad del modelo:')
print(sensibilidad)

sensibilidad del modelo:
0.47857482939215995


In [43]:
#El puntaje F1 que es una combinación entre la precisión y la sensibilidad,
#Calculo el puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajeF1=f1_score(y_test,y_pred,average='binary',pos_label=0)
print('Puntaje F1 del modelo')
print(puntajeF1)

Puntaje F1 del modelo
0.49188483810455913


Experimento 4

In [44]:
#Declarar variables
Vars_Indep= df[['Experience']]
Var_Dep= df['Income_bool']

#Redefinir las variables
x= Vars_Indep
y= Var_Dep

#Dividir el conjunto de datos en la parte de entrenamiento y prueba:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= None)

#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "x" tanto de entrenamiento como de prueba,
#solo se escala una variable y de tipo dicotonimca
x_train = escalar.fit_transform(x_train)
x_test = escalar.fit_transform(x_test)

#Definir el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenar el modelo
algoritmo.fit(x_train, y_train)

LogisticRegression()

In [45]:
#Realizar una predicción
y_pred = algoritmo.predict(x_test)
y_pred

array([0, 0, 0, ..., 1, 1, 0])

In [46]:
#Verificar la matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[14441 10662]
 [14809 10488]]


In [47]:
#Cálculo de la presición del modelo
#para tener una mejor precisión debemos de cambiar el numero de variables predictoras (y)
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average= "binary", pos_label=0)
print('Precisión de modelo: ')
print(precision)

Precisión de modelo: 
0.4937094017094017


In [48]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo: ')
print(exactitud)

Exactitud del modelo: 
0.4946230158730159


In [49]:
#calculo de la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test,y_pred, average='binary', pos_label=0)
print('sensibilidad del modelo:')
print(sensibilidad)

sensibilidad del modelo:
0.575269888061188


In [50]:
#El puntaje F1 que es una combinación entre la precisión y la sensibilidad,
#Calculo el puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajeF1=f1_score(y_test,y_pred,average='binary',pos_label=0)
print('Puntaje F1 del modelo')
print(puntajeF1)

Puntaje F1 del modelo
0.531378212794142
